import Topnavs from "@/components/ah-topnavs";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Layout/ah-footer";
// import { FKGrotesk } from "./styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans relative bg-angel-blue w-full">
        <Topnavs />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
