import type { Metadata } from "next";
import "./globals.css";
// import { FKGrotesk } from "./styles/fonts";
import Topnavs from "./components/ah-topnavs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans relative bg-angel-blue w-full">
        <Topnavs />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
